apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: nginx        # Matches your Pod labels: app=nginx
  ports:
    - protocol: TCP
      port: 80         # Port accessible within the cluster
      targetPort: 80   # Port Apache is listening on inside the container
      nodePort: 30080  # Port you will use in your browser
